#-------------------------------
# Site Settings
title: Ur Lawyer | your trusted guide to U.S. law
logo: /images/logo.webp
logo_text: Ur Lawyer
description: your trusted guide to U.S. law. Learn about personal injury, divorce, immigration, employment, criminal, tax, and accident lawyers. Get practical legal advice for every situation.


#-------------------------------
# Author Global Settings
author:
  - author__name: Ur Lawyer Garen
    author__bio: I worked for 12 years in Los Angeles and San Francisco Bay Area as a trial lawyer, mainly in criminal defense but also as a plaintiff's lawyer in Asbestos related civil litigation.
    author__avatar: /images/Lawyer-Garen.webp
  - author__name: Ur Lawyer Mary
    author__bio:  I am a personal injury and trucking trial lawyer who helps people injured by commercial motor vehicles, and their families, receive fair treatment by insurance companies. 
    author__avatar: /images/Lawyer-Mary.webp


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Authors'
      url: '/authors/' 
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Your Trusted Legal Guide for Every Case in the U.S


#-------------------------------
# Blog Settings
blog:
  blog__title: Blog & Resources
  blog__description: Learn about personal injury, divorce, immigration, employment, criminal, tax, and accident lawyers. Get practical legal advice for every situation.



#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Recommended
  tag__name: Motivation


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts.
  mailchimp__input__text: Your Email Address...
  mailchimp__button__text: Subscribe
  mailchimp__background__image: "/images/110.jpg"


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Privacy Policy'
      url: '/privacy-policy/'
    - title: 'Disclaimer'
      url: '/disclaimer/'
    - title: 'Terms and Conditions'
      url: '/terms-and-conditions/'
    - title: 'Authors'
      url: '/authors/'


# Social Links
social:
- {icon: "ion-logo-twitter", color: "#55acee", name: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", color: "#3b5999", name: Facebook, link: "https://facebook.com"}
- {icon: "ion-logo-pinterest", color: "#bd081c", name: Pinterest, link: "https://pinterest.com"}
- {icon: "ion-logo-dribbble", color: "#ea4c89", name: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", name: Instagram, link: "https://instagram.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-youtube", color: "#ff0000", name: Youtube, link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contant form

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id